### ISSUE TITLE
Film palast,Szene stream,gamestar gehen nicht .

### ISSUE THREAD

**Issue by shagger** [LaryLoose/laryloose.xbmc-addons#16]
Hallo Larry,

Es wäre schön wenn du hier deine addons updates. Gamestar geht gar nicht. Filmpalast läuft  nicht mehr....bzw. findet keine hoster/filme.es gab zwar bei Szene streams keine neuen Filme mehr, es fehlen aber hoster.
Danke im voraus 

Film Palast geht wieder-braucht aber sehr lange bis die Filme und hysterisch geladen werden. Stand:14.10.16

Shagger

**Comment by firetv2user** [comment]
Filmpalast funktioniert seit ein paar Tagen nicht mehr. Das Laden der Hosterliste dauert sehr lange und endet dann in einer Fehlermeldung (Wiedergabe nicht möglich. Mindestens eine Datei konnte nicht ...).

Szene-Streams funktioniert schon seit einigen Wochen nicht mehr. Neueste Filme Auflistung ist seitdem immer gleich. Die Hosterliste der einzelnen Filme wird zwar geladen, kann aber nicht abgespielt werden (Wiedergabe nicht möglich. Mindestens eine Datei konnte nicht ...).

Update 21.10.2016: Filmpalast ist seit mindestens gestern down.

**Comment by elmin1984** [comment]
Hi filmpalast geht nicht es versucht
lange zu laden dann bricht es ab wäre schön wenn es wieder läuft 👍👌
