### ISSUE TITLE
1kino and movie-paradise don't work 

### ISSUE THREAD

**Issue by shagger** [LaryLoose/laryloose.xbmc-addons#6]
Hello Larry,
Great work .your repo ist brillant. Since  a few days I get deleted Videos"Videos nicht gefunden" with the movie -paradise addon.
The 1kino addon gets errors since dec.14.
Could you please fix it.

Thanks for your scipts.
shagger

**Comment by firetv2user** [comment]
I can confirm this issue with the movie-paradise addon. The videos are listed, but cannot be found.

K1no addon doesn' work at all on Fire TV Stick 2.
